name: sql_class_annotation
version: 0.0.1
description: >-
  Classes and helper functions that support Dart Class code generation via the
  `sql_class_serializable` package.
homepage:
author: author:Cat-x <a599231042@163.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

# When changing JsonSerializable class.
# dev_dependencies:
#   build_runner: ^1.0.0
#   sql_data_serializable: ^0.0.1